### ISSUE TITLE
[Noetic] skyway fails to build on arm64 and armhf

### ISSUE THREAD

**Issue by sloretz** [ntt-t3/skyway_for_ros#1]
Hey @nakakura,

It looks like `skyway` isn't building on some platforms:

* [Ubuntu Focal arm64](https://build.ros.org/job/Nbin_ufv8_uFv8__skyway__ubuntu_focal_arm64__binary/)
* [Ubuntu Focal armhf](https://build.ros.org/job/Nbin_ufhf_uFhf__rwt_app_chooser__ubuntu_focal_armhf__binary/)

I'm planning to add all chronically failing packages to per-platform blacklists later this week.
That just means the buildfarm won't try to build them every day.

When all issues causing the build failures are resolved, please make a PR to the `production` branch on [ros_buildfarm_config](https://github.com/ros-infrastructure/ros_buildfarm_config/tree/production/noetic) removing it from the `package_blacklist`:

* [release-arm64-build.yaml](https://github.com/ros-infrastructure/ros_buildfarm_config/blob/production/noetic/release-arm64-build.yaml)
* [release-armhf-build.yaml](https://github.com/ros-infrastructure/ros_buildfarm_config/blob/production/noetic/release-armhf-build.yaml)

**Comment by nakakura** [comment]
Sorry for the delay in confirming. Noted. I will correct it.
